/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RoommatesRouteImport } from './routes/roommates'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as ListingsListingIdRouteImport } from './routes/listings.$listingId'
import { Route as OnboardingOwnerRouteImport } from './routes/onboarding.owner'
import { Route as OnboardingScoutRouteImport } from './routes/onboarding.scout'
import { Route as OnboardingStudentRouteImport } from './routes/onboarding.student'
import { Route as OwnerBookingsRouteImport } from './routes/owner/bookings'
import { Route as OwnerPropertiesRouteImport } from './routes/owner/properties'
import { Route as ScoutActivityRouteImport } from './routes/scout/activity'
import { Route as ScoutBookingsRouteImport } from './routes/scout/bookings'
import { Route as ScoutPropertiesRouteImport } from './routes/scout/properties'
import { Route as OwnerPropertiesPropertyIdRouteImport } from './routes/owner/properties/$propertyId'
import { Route as OwnerPropertiesNewRouteImport } from './routes/owner/properties/new'
import { Route as ScoutPropertiesPropertyIdRouteImport } from './routes/scout/properties/$propertyId'
import { Route as OwnerPropertiesPropertyIdAvailabilityRouteImport } from './routes/owner/properties/$propertyId/availability'
import { Route as OwnerPropertiesPropertyIdEditRouteImport } from './routes/owner/properties/$propertyId/edit'
import { Route as ScoutPropertiesPropertyIdAvailabilityRouteImport } from './routes/scout/properties/$propertyId/availability'
import { Route as ScoutPropertiesPropertyIdEditRouteImport } from './routes/scout/properties/$propertyId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RoommatesRoute = RoommatesRouteImport.update({
  id: '/roommates',
  path: '/roommates',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsListingIdRoute = ListingsListingIdRouteImport.update({
  id: '/listings/$listingId',
  path: '/listings/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOwnerRoute = OnboardingOwnerRouteImport.update({
  id: '/onboarding/owner',
  path: '/onboarding/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingScoutRoute = OnboardingScoutRouteImport.update({
  id: '/onboarding/scout',
  path: '/onboarding/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStudentRoute = OnboardingStudentRouteImport.update({
  id: '/onboarding/student',
  path: '/onboarding/student',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerBookingsRoute = OwnerBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerPropertiesRoute = OwnerPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => OwnerRoute,
} as any)
const ScoutActivityRoute = ScoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => ScoutRoute,
} as any)
const ScoutBookingsRoute = ScoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => ScoutRoute,
} as any)
const ScoutPropertiesRoute = ScoutPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => ScoutRoute,
} as any)
const OwnerPropertiesPropertyIdRoute =
  OwnerPropertiesPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => OwnerPropertiesRoute,
  } as any)
const OwnerPropertiesNewRoute = OwnerPropertiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OwnerPropertiesRoute,
} as any)
const ScoutPropertiesPropertyIdRoute =
  ScoutPropertiesPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => ScoutPropertiesRoute,
  } as any)
const OwnerPropertiesPropertyIdAvailabilityRoute =
  OwnerPropertiesPropertyIdAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => OwnerPropertiesPropertyIdRoute,
  } as any)
const OwnerPropertiesPropertyIdEditRoute =
  OwnerPropertiesPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => OwnerPropertiesPropertyIdRoute,
  } as any)
const ScoutPropertiesPropertyIdAvailabilityRoute =
  ScoutPropertiesPropertyIdAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => ScoutPropertiesPropertyIdRoute,
  } as any)
const ScoutPropertiesPropertyIdEditRoute =
  ScoutPropertiesPropertyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ScoutPropertiesPropertyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/roommates': typeof RoommatesRoute
  '/saved': typeof SavedRoute
  '/scout': typeof ScoutRouteWithChildren
  '/select-role': typeof SelectRoleRoute
  '/verify': typeof VerifyRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/onboarding/owner': typeof OnboardingOwnerRoute
  '/onboarding/scout': typeof OnboardingScoutRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/scout/activity': typeof ScoutActivityRoute
  '/scout/bookings': typeof ScoutBookingsRoute
  '/scout/properties': typeof ScoutPropertiesRouteWithChildren
  '/owner/properties/$propertyId': typeof OwnerPropertiesPropertyIdRouteWithChildren
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/scout/properties/$propertyId': typeof ScoutPropertiesPropertyIdRouteWithChildren
  '/owner/properties/$propertyId/availability': typeof OwnerPropertiesPropertyIdAvailabilityRoute
  '/owner/properties/$propertyId/edit': typeof OwnerPropertiesPropertyIdEditRoute
  '/scout/properties/$propertyId/availability': typeof ScoutPropertiesPropertyIdAvailabilityRoute
  '/scout/properties/$propertyId/edit': typeof ScoutPropertiesPropertyIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/roommates': typeof RoommatesRoute
  '/saved': typeof SavedRoute
  '/scout': typeof ScoutRouteWithChildren
  '/select-role': typeof SelectRoleRoute
  '/verify': typeof VerifyRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/onboarding/owner': typeof OnboardingOwnerRoute
  '/onboarding/scout': typeof OnboardingScoutRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/scout/activity': typeof ScoutActivityRoute
  '/scout/bookings': typeof ScoutBookingsRoute
  '/scout/properties': typeof ScoutPropertiesRouteWithChildren
  '/owner/properties/$propertyId': typeof OwnerPropertiesPropertyIdRouteWithChildren
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/scout/properties/$propertyId': typeof ScoutPropertiesPropertyIdRouteWithChildren
  '/owner/properties/$propertyId/availability': typeof OwnerPropertiesPropertyIdAvailabilityRoute
  '/owner/properties/$propertyId/edit': typeof OwnerPropertiesPropertyIdEditRoute
  '/scout/properties/$propertyId/availability': typeof ScoutPropertiesPropertyIdAvailabilityRoute
  '/scout/properties/$propertyId/edit': typeof ScoutPropertiesPropertyIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/discover': typeof DiscoverRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/owner': typeof OwnerRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/roommates': typeof RoommatesRoute
  '/saved': typeof SavedRoute
  '/scout': typeof ScoutRouteWithChildren
  '/select-role': typeof SelectRoleRoute
  '/verify': typeof VerifyRoute
  '/listings/$listingId': typeof ListingsListingIdRoute
  '/onboarding/owner': typeof OnboardingOwnerRoute
  '/onboarding/scout': typeof OnboardingScoutRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/owner/bookings': typeof OwnerBookingsRoute
  '/owner/properties': typeof OwnerPropertiesRouteWithChildren
  '/scout/activity': typeof ScoutActivityRoute
  '/scout/bookings': typeof ScoutBookingsRoute
  '/scout/properties': typeof ScoutPropertiesRouteWithChildren
  '/owner/properties/$propertyId': typeof OwnerPropertiesPropertyIdRouteWithChildren
  '/owner/properties/new': typeof OwnerPropertiesNewRoute
  '/scout/properties/$propertyId': typeof ScoutPropertiesPropertyIdRouteWithChildren
  '/owner/properties/$propertyId/availability': typeof OwnerPropertiesPropertyIdAvailabilityRoute
  '/owner/properties/$propertyId/edit': typeof OwnerPropertiesPropertyIdEditRoute
  '/scout/properties/$propertyId/availability': typeof ScoutPropertiesPropertyIdAvailabilityRoute
  '/scout/properties/$propertyId/edit': typeof ScoutPropertiesPropertyIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/discover'
    | '/login'
    | '/messages'
    | '/owner'
    | '/profile'
    | '/register'
    | '/roommates'
    | '/saved'
    | '/scout'
    | '/select-role'
    | '/verify'
    | '/listings/$listingId'
    | '/onboarding/owner'
    | '/onboarding/scout'
    | '/onboarding/student'
    | '/owner/bookings'
    | '/owner/properties'
    | '/scout/activity'
    | '/scout/bookings'
    | '/scout/properties'
    | '/owner/properties/$propertyId'
    | '/owner/properties/new'
    | '/scout/properties/$propertyId'
    | '/owner/properties/$propertyId/availability'
    | '/owner/properties/$propertyId/edit'
    | '/scout/properties/$propertyId/availability'
    | '/scout/properties/$propertyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/discover'
    | '/login'
    | '/messages'
    | '/owner'
    | '/profile'
    | '/register'
    | '/roommates'
    | '/saved'
    | '/scout'
    | '/select-role'
    | '/verify'
    | '/listings/$listingId'
    | '/onboarding/owner'
    | '/onboarding/scout'
    | '/onboarding/student'
    | '/owner/bookings'
    | '/owner/properties'
    | '/scout/activity'
    | '/scout/bookings'
    | '/scout/properties'
    | '/owner/properties/$propertyId'
    | '/owner/properties/new'
    | '/scout/properties/$propertyId'
    | '/owner/properties/$propertyId/availability'
    | '/owner/properties/$propertyId/edit'
    | '/scout/properties/$propertyId/availability'
    | '/scout/properties/$propertyId/edit'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/discover'
    | '/login'
    | '/messages'
    | '/owner'
    | '/profile'
    | '/register'
    | '/roommates'
    | '/saved'
    | '/scout'
    | '/select-role'
    | '/verify'
    | '/listings/$listingId'
    | '/onboarding/owner'
    | '/onboarding/scout'
    | '/onboarding/student'
    | '/owner/bookings'
    | '/owner/properties'
    | '/scout/activity'
    | '/scout/bookings'
    | '/scout/properties'
    | '/owner/properties/$propertyId'
    | '/owner/properties/new'
    | '/scout/properties/$propertyId'
    | '/owner/properties/$propertyId/availability'
    | '/owner/properties/$propertyId/edit'
    | '/scout/properties/$propertyId/availability'
    | '/scout/properties/$propertyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  DiscoverRoute: typeof DiscoverRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RoommatesRoute: typeof RoommatesRoute
  SavedRoute: typeof SavedRoute
  ScoutRoute: typeof ScoutRouteWithChildren
  SelectRoleRoute: typeof SelectRoleRoute
  VerifyRoute: typeof VerifyRoute
  ListingsListingIdRoute: typeof ListingsListingIdRoute
  OnboardingOwnerRoute: typeof OnboardingOwnerRoute
  OnboardingScoutRoute: typeof OnboardingScoutRoute
  OnboardingStudentRoute: typeof OnboardingStudentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roommates': {
      id: '/roommates'
      path: '/roommates'
      fullPath: '/roommates'
      preLoaderRoute: typeof RoommatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$listingId': {
      id: '/listings/$listingId'
      path: '/listings/$listingId'
      fullPath: '/listings/$listingId'
      preLoaderRoute: typeof ListingsListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/owner': {
      id: '/onboarding/owner'
      path: '/onboarding/owner'
      fullPath: '/onboarding/owner'
      preLoaderRoute: typeof OnboardingOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/scout': {
      id: '/onboarding/scout'
      path: '/onboarding/scout'
      fullPath: '/onboarding/scout'
      preLoaderRoute: typeof OnboardingScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/student': {
      id: '/onboarding/student'
      path: '/onboarding/student'
      fullPath: '/onboarding/student'
      preLoaderRoute: typeof OnboardingStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/bookings': {
      id: '/owner/bookings'
      path: '/bookings'
      fullPath: '/owner/bookings'
      preLoaderRoute: typeof OwnerBookingsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/properties': {
      id: '/owner/properties'
      path: '/properties'
      fullPath: '/owner/properties'
      preLoaderRoute: typeof OwnerPropertiesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/scout/activity': {
      id: '/scout/activity'
      path: '/activity'
      fullPath: '/scout/activity'
      preLoaderRoute: typeof ScoutActivityRouteImport
      parentRoute: typeof ScoutRoute
    }
    '/scout/bookings': {
      id: '/scout/bookings'
      path: '/bookings'
      fullPath: '/scout/bookings'
      preLoaderRoute: typeof ScoutBookingsRouteImport
      parentRoute: typeof ScoutRoute
    }
    '/scout/properties': {
      id: '/scout/properties'
      path: '/properties'
      fullPath: '/scout/properties'
      preLoaderRoute: typeof ScoutPropertiesRouteImport
      parentRoute: typeof ScoutRoute
    }
    '/owner/properties/$propertyId': {
      id: '/owner/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/owner/properties/$propertyId'
      preLoaderRoute: typeof OwnerPropertiesPropertyIdRouteImport
      parentRoute: typeof OwnerPropertiesRoute
    }
    '/owner/properties/new': {
      id: '/owner/properties/new'
      path: '/new'
      fullPath: '/owner/properties/new'
      preLoaderRoute: typeof OwnerPropertiesNewRouteImport
      parentRoute: typeof OwnerPropertiesRoute
    }
    '/scout/properties/$propertyId': {
      id: '/scout/properties/$propertyId'
      path: '/$propertyId'
      fullPath: '/scout/properties/$propertyId'
      preLoaderRoute: typeof ScoutPropertiesPropertyIdRouteImport
      parentRoute: typeof ScoutPropertiesRoute
    }
    '/owner/properties/$propertyId/availability': {
      id: '/owner/properties/$propertyId/availability'
      path: '/availability'
      fullPath: '/owner/properties/$propertyId/availability'
      preLoaderRoute: typeof OwnerPropertiesPropertyIdAvailabilityRouteImport
      parentRoute: typeof OwnerPropertiesPropertyIdRoute
    }
    '/owner/properties/$propertyId/edit': {
      id: '/owner/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/owner/properties/$propertyId/edit'
      preLoaderRoute: typeof OwnerPropertiesPropertyIdEditRouteImport
      parentRoute: typeof OwnerPropertiesPropertyIdRoute
    }
    '/scout/properties/$propertyId/availability': {
      id: '/scout/properties/$propertyId/availability'
      path: '/availability'
      fullPath: '/scout/properties/$propertyId/availability'
      preLoaderRoute: typeof ScoutPropertiesPropertyIdAvailabilityRouteImport
      parentRoute: typeof ScoutPropertiesPropertyIdRoute
    }
    '/scout/properties/$propertyId/edit': {
      id: '/scout/properties/$propertyId/edit'
      path: '/edit'
      fullPath: '/scout/properties/$propertyId/edit'
      preLoaderRoute: typeof ScoutPropertiesPropertyIdEditRouteImport
      parentRoute: typeof ScoutPropertiesPropertyIdRoute
    }
  }
}

interface OwnerPropertiesPropertyIdRouteChildren {
  OwnerPropertiesPropertyIdAvailabilityRoute: typeof OwnerPropertiesPropertyIdAvailabilityRoute
  OwnerPropertiesPropertyIdEditRoute: typeof OwnerPropertiesPropertyIdEditRoute
}

const OwnerPropertiesPropertyIdRouteChildren: OwnerPropertiesPropertyIdRouteChildren =
  {
    OwnerPropertiesPropertyIdAvailabilityRoute:
      OwnerPropertiesPropertyIdAvailabilityRoute,
    OwnerPropertiesPropertyIdEditRoute: OwnerPropertiesPropertyIdEditRoute,
  }

const OwnerPropertiesPropertyIdRouteWithChildren =
  OwnerPropertiesPropertyIdRoute._addFileChildren(
    OwnerPropertiesPropertyIdRouteChildren,
  )

interface OwnerPropertiesRouteChildren {
  OwnerPropertiesPropertyIdRoute: typeof OwnerPropertiesPropertyIdRouteWithChildren
  OwnerPropertiesNewRoute: typeof OwnerPropertiesNewRoute
}

const OwnerPropertiesRouteChildren: OwnerPropertiesRouteChildren = {
  OwnerPropertiesPropertyIdRoute: OwnerPropertiesPropertyIdRouteWithChildren,
  OwnerPropertiesNewRoute: OwnerPropertiesNewRoute,
}

const OwnerPropertiesRouteWithChildren = OwnerPropertiesRoute._addFileChildren(
  OwnerPropertiesRouteChildren,
)

interface OwnerRouteChildren {
  OwnerBookingsRoute: typeof OwnerBookingsRoute
  OwnerPropertiesRoute: typeof OwnerPropertiesRouteWithChildren
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerBookingsRoute: OwnerBookingsRoute,
  OwnerPropertiesRoute: OwnerPropertiesRouteWithChildren,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

interface ScoutPropertiesPropertyIdRouteChildren {
  ScoutPropertiesPropertyIdAvailabilityRoute: typeof ScoutPropertiesPropertyIdAvailabilityRoute
  ScoutPropertiesPropertyIdEditRoute: typeof ScoutPropertiesPropertyIdEditRoute
}

const ScoutPropertiesPropertyIdRouteChildren: ScoutPropertiesPropertyIdRouteChildren =
  {
    ScoutPropertiesPropertyIdAvailabilityRoute:
      ScoutPropertiesPropertyIdAvailabilityRoute,
    ScoutPropertiesPropertyIdEditRoute: ScoutPropertiesPropertyIdEditRoute,
  }

const ScoutPropertiesPropertyIdRouteWithChildren =
  ScoutPropertiesPropertyIdRoute._addFileChildren(
    ScoutPropertiesPropertyIdRouteChildren,
  )

interface ScoutPropertiesRouteChildren {
  ScoutPropertiesPropertyIdRoute: typeof ScoutPropertiesPropertyIdRouteWithChildren
}

const ScoutPropertiesRouteChildren: ScoutPropertiesRouteChildren = {
  ScoutPropertiesPropertyIdRoute: ScoutPropertiesPropertyIdRouteWithChildren,
}

const ScoutPropertiesRouteWithChildren = ScoutPropertiesRoute._addFileChildren(
  ScoutPropertiesRouteChildren,
)

interface ScoutRouteChildren {
  ScoutActivityRoute: typeof ScoutActivityRoute
  ScoutBookingsRoute: typeof ScoutBookingsRoute
  ScoutPropertiesRoute: typeof ScoutPropertiesRouteWithChildren
}

const ScoutRouteChildren: ScoutRouteChildren = {
  ScoutActivityRoute: ScoutActivityRoute,
  ScoutBookingsRoute: ScoutBookingsRoute,
  ScoutPropertiesRoute: ScoutPropertiesRouteWithChildren,
}

const ScoutRouteWithChildren = ScoutRoute._addFileChildren(ScoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  DiscoverRoute: DiscoverRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  OwnerRoute: OwnerRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RoommatesRoute: RoommatesRoute,
  SavedRoute: SavedRoute,
  ScoutRoute: ScoutRouteWithChildren,
  SelectRoleRoute: SelectRoleRoute,
  VerifyRoute: VerifyRoute,
  ListingsListingIdRoute: ListingsListingIdRoute,
  OnboardingOwnerRoute: OnboardingOwnerRoute,
  OnboardingScoutRoute: OnboardingScoutRoute,
  OnboardingStudentRoute: OnboardingStudentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
